# For more details, please see https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true

ports:
  - port: 5432
    onOpen: open-preview

  - port: 5050
    onOpen: open-preview

  - port: 50606
    onOpen: open-preview